### ISSUE TITLE
LND web dashboard

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#63]
Check out and possibly add https://github.com/mably/lncli-web container

**Comment by AnotherDroog** [comment]
`docker build . -t lncli-web` from our forked repo currently fails with:

```
> grpc@1.17.0 install /lncli-web/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.17.0/node-v57-linux-arm-musl.tar.gz                                                        node-pre-gyp WARN Pre-built binaries not found for grpc@1.17.0 and node@8.14.0 (node-v57 ABI, musl) (falling back to source compile with node-gyp)                                     make: Entering directory '/lncli-web/node_modules/grpc/build'
  CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/cpu_posix.o
  CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/cpu_windows.o
... omitted for brevity...
  CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/profiling/basic_timers.o
  CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/profiling/stap_timers.o
  AR(target) Release/obj.target/libgpr.a
  COPY Release/libgpr.a
  CXX(target) Release/obj.target/grpc_node/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc_node/ext/call.o
In file included from ../ext/call.cc:26:0:
../ext/call.h:108:8: error: 'AsyncResource' in namespace 'Nan' does not name a type
   Nan::AsyncResource *async_resource;
        ^~~~~~~~~~~~~
In file included from ../ext/call.cc:27:0:
../ext/call_credentials.h:82:8: error: 'AsyncResource' in namespace 'Nan' does not name a type
In file included from ../ext/call.cc:27:0:                                                                                                                                   
../ext/call_credentials.h:82:8: error: 'AsyncResource' in namespace 'Nan' does not name a type
   Nan::AsyncResource *async_resource;
        ^~~~~~~~~~~~~
../ext/call_credentials.h: In constructor 'grpc::node::plugin_callback_data::plugin_callback_data(const char*, grpc_credentials_plugin_metadata_cb, void*)':
../ext/call_credentials.h:71:9: error: class 'grpc::node::plugin_callback_data' does not have any field named 'async_resource'                                                                  async_resource(NULL) {                                                                                                                                                                 ^~~~~~~~~~~~~~
../ext/call_credentials.h:73:5: error: 'async_resource' was not declared in this scope
     async_resource = new Nan::AsyncResource("grpc:plugin_callback_data");
     ^~~~~~~~~~~~~~
../ext/call_credentials.h:73:26: error: expected type-specifier
     async_resource = new Nan::AsyncResource("grpc:plugin_callback_data");
                          ^~~                                                                                                                                                          ../ext/call_credentials.h: In destructor 'grpc::node::plugin_callback_data::~plugin_callback_data()':                                                                                  ../ext/call_credentials.h:76:12: error: 'async_resource' was not declared in this scope
     delete async_resource;
            ^~~~~~~~~~~~~~
../ext/call.cc: In constructor 'grpc::node::tag::tag(Nan::Callback*, grpc::node::OpVec*, grpc::node::Call*, v8::Local<v8::Value>)':
../ext/call.cc:450:7: error: class 'grpc::node::tag' does not have any field named 'async_resource'
       async_resource(NULL),
       ^~~~~~~~~~~~~~
../ext/call.cc:454:3: error: 'async_resource' was not declared in this scope
   async_resource = new Nan::AsyncResource("grpc:tag");  // Needs handle scope.
   ^~~~~~~~~~~~~~
../ext/call.cc:454:24: error: expected type-specifier
   async_resource = new Nan::AsyncResource("grpc:tag");  // Needs handle scope.
                        ^~~                                                                                                                                                            ../ext/call.cc: In destructor 'grpc::node::tag::~tag()':                                                                                                                               ../ext/call.cc:460:10: error: 'async_resource' was not declared in this scope
   delete async_resource;
          ^~~~~~~~~~~~~~
../ext/call.cc: In function 'void grpc::node::CompleteTag(void*, const char*)':
../ext/call.cc:476:41: error: 'struct grpc::node::tag' has no member named 'async_resource'
     callback->Call(2, argv, tag_struct->async_resource);
                                         ^~~~~~~~~~~~~~
../ext/call.cc:479:41: error: 'struct grpc::node::tag' has no member named 'async_resource'
     callback->Call(1, argv, tag_struct->async_resource);
                                         ^~~~~~~~~~~~~~
make: *** [grpc_node.target.mk:176: Release/obj.target/grpc_node/ext/call.o] Error 1
make: Leaving directory '/lncli-web/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)                                                                [0/1918]
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.89-0-rpi2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/lncli-web/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/lncli-web/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-musl" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /lncli-web/node_modules/grpc
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/lncli-web/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/lncli-web/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-musl --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/lncli-web/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.14.89-0-rpi2
node-pre-gyp ERR! command "/usr/bin/node" "/lncli-web/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /lncli-web/node_modules/grpc
node-pre-gyp ERR! node -v v8.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/lncli-web/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-musl/grpc_node.node --module_name=grpc_node --module_path=/lncli-web/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-musl --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.17.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.17.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-29T10_07_05_803Z-debug.log
The command '/bin/sh -c apk add --no-cache nodejs npm python make g++ && npm install &&  ./node_modules/.bin/gulp bundles' returned a non-zero code: 1
```

**Comment by AnotherDroog** [comment]
Check out this one: https://github.com/djmelik/lndash

**Comment by AnotherDroog** [comment]
Would be great to get lndash built on ARM

**Comment by nolim1t** [comment]
Closing in favor of #236  we can add this into a separate module
